/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** Direction of desired links */
@org.apache.avro.specific.AvroGenerated
public enum FL_DirectionFilter { 
  SOURCE, DESTINATION, BOTH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FL_DirectionFilter\",\"namespace\":\"influent.idl\",\"doc\":\"Direction of desired links\",\"symbols\":[\"SOURCE\",\"DESTINATION\",\"BOTH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
