/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** This is a placeholder for timeseries and other series that are available as property values, which the UI will use to make
	 charts. This may come back from aggregating links. */
@org.apache.avro.specific.AvroGenerated
public class FL_Series extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FL_Series\",\"namespace\":\"influent.idl\",\"doc\":\"This is a placeholder for timeseries and other series that are available as property values, which the UI will use to make\\r\\n\\t charts. This may come back from aggregating links.\",\"fields\":[]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /** Creates a new FL_Series RecordBuilder */
  public static influent.idl.FL_Series.Builder newBuilder() {
    return new influent.idl.FL_Series.Builder();
  }
  
  /** Creates a new FL_Series RecordBuilder by copying an existing Builder */
  public static influent.idl.FL_Series.Builder newBuilder(influent.idl.FL_Series.Builder other) {
    return new influent.idl.FL_Series.Builder(other);
  }
  
  /** Creates a new FL_Series RecordBuilder by copying an existing FL_Series instance */
  public static influent.idl.FL_Series.Builder newBuilder(influent.idl.FL_Series other) {
    return new influent.idl.FL_Series.Builder(other);
  }
  
  /**
   * RecordBuilder for FL_Series instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FL_Series>
    implements org.apache.avro.data.RecordBuilder<FL_Series> {


    /** Creates a new Builder */
    private Builder() {
      super(influent.idl.FL_Series.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(influent.idl.FL_Series.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing FL_Series instance */
    private Builder(influent.idl.FL_Series other) {
            super(influent.idl.FL_Series.SCHEMA$);
    }

    public FL_Series build() {
      try {
        FL_Series record = new FL_Series();
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
