/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package influent.idl;  
@SuppressWarnings("all")
/** Structured representation of geo-spatial data. */
@org.apache.avro.specific.AvroGenerated
public class FL_GeoData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FL_GeoData\",\"namespace\":\"influent.idl\",\"doc\":\"Structured representation of geo-spatial data.\",\"fields\":[{\"name\":\"text\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"doc\":\"an address or other place reference; unstructured text field\",\"default\":null},{\"name\":\"lat\",\"type\":[\"double\",\"null\"],\"doc\":\"latitude\",\"default\":null},{\"name\":\"lon\",\"type\":[\"double\",\"null\"],\"doc\":\"longitude\",\"default\":null},{\"name\":\"cc\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"],\"doc\":\"ISO 3 digit country code\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** an address or other place reference; unstructured text field */
   private java.lang.String text;
  /** latitude */
   private java.lang.Double lat;
  /** longitude */
   private java.lang.Double lon;
  /** ISO 3 digit country code */
   private java.lang.String cc;

  /**
   * Default constructor.
   */
  public FL_GeoData() {}

  /**
   * All-args constructor.
   */
  public FL_GeoData(java.lang.String text, java.lang.Double lat, java.lang.Double lon, java.lang.String cc) {
    this.text = text;
    this.lat = lat;
    this.lon = lon;
    this.cc = cc;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return text;
    case 1: return lat;
    case 2: return lon;
    case 3: return cc;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: text = (java.lang.String)value$; break;
    case 1: lat = (java.lang.Double)value$; break;
    case 2: lon = (java.lang.Double)value$; break;
    case 3: cc = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'text' field.
   * an address or other place reference; unstructured text field   */
  public java.lang.String getText() {
    return text;
  }

  /**
   * Sets the value of the 'text' field.
   * an address or other place reference; unstructured text field   * @param value the value to set.
   */
  public void setText(java.lang.String value) {
    this.text = value;
  }

  /**
   * Gets the value of the 'lat' field.
   * latitude   */
  public java.lang.Double getLat() {
    return lat;
  }

  /**
   * Sets the value of the 'lat' field.
   * latitude   * @param value the value to set.
   */
  public void setLat(java.lang.Double value) {
    this.lat = value;
  }

  /**
   * Gets the value of the 'lon' field.
   * longitude   */
  public java.lang.Double getLon() {
    return lon;
  }

  /**
   * Sets the value of the 'lon' field.
   * longitude   * @param value the value to set.
   */
  public void setLon(java.lang.Double value) {
    this.lon = value;
  }

  /**
   * Gets the value of the 'cc' field.
   * ISO 3 digit country code   */
  public java.lang.String getCc() {
    return cc;
  }

  /**
   * Sets the value of the 'cc' field.
   * ISO 3 digit country code   * @param value the value to set.
   */
  public void setCc(java.lang.String value) {
    this.cc = value;
  }

  /** Creates a new FL_GeoData RecordBuilder */
  public static influent.idl.FL_GeoData.Builder newBuilder() {
    return new influent.idl.FL_GeoData.Builder();
  }
  
  /** Creates a new FL_GeoData RecordBuilder by copying an existing Builder */
  public static influent.idl.FL_GeoData.Builder newBuilder(influent.idl.FL_GeoData.Builder other) {
    return new influent.idl.FL_GeoData.Builder(other);
  }
  
  /** Creates a new FL_GeoData RecordBuilder by copying an existing FL_GeoData instance */
  public static influent.idl.FL_GeoData.Builder newBuilder(influent.idl.FL_GeoData other) {
    return new influent.idl.FL_GeoData.Builder(other);
  }
  
  /**
   * RecordBuilder for FL_GeoData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FL_GeoData>
    implements org.apache.avro.data.RecordBuilder<FL_GeoData> {

    private java.lang.String text;
    private java.lang.Double lat;
    private java.lang.Double lon;
    private java.lang.String cc;

    /** Creates a new Builder */
    private Builder() {
      super(influent.idl.FL_GeoData.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(influent.idl.FL_GeoData.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing FL_GeoData instance */
    private Builder(influent.idl.FL_GeoData other) {
            super(influent.idl.FL_GeoData.SCHEMA$);
      if (isValidValue(fields()[0], other.text)) {
        this.text = data().deepCopy(fields()[0].schema(), other.text);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.lon)) {
        this.lon = data().deepCopy(fields()[2].schema(), other.lon);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.cc)) {
        this.cc = data().deepCopy(fields()[3].schema(), other.cc);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'text' field */
    public java.lang.String getText() {
      return text;
    }
    
    /** Sets the value of the 'text' field */
    public influent.idl.FL_GeoData.Builder setText(java.lang.String value) {
      validate(fields()[0], value);
      this.text = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'text' field has been set */
    public boolean hasText() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'text' field */
    public influent.idl.FL_GeoData.Builder clearText() {
      text = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'lat' field */
    public java.lang.Double getLat() {
      return lat;
    }
    
    /** Sets the value of the 'lat' field */
    public influent.idl.FL_GeoData.Builder setLat(java.lang.Double value) {
      validate(fields()[1], value);
      this.lat = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'lat' field has been set */
    public boolean hasLat() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'lat' field */
    public influent.idl.FL_GeoData.Builder clearLat() {
      lat = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'lon' field */
    public java.lang.Double getLon() {
      return lon;
    }
    
    /** Sets the value of the 'lon' field */
    public influent.idl.FL_GeoData.Builder setLon(java.lang.Double value) {
      validate(fields()[2], value);
      this.lon = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'lon' field has been set */
    public boolean hasLon() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'lon' field */
    public influent.idl.FL_GeoData.Builder clearLon() {
      lon = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'cc' field */
    public java.lang.String getCc() {
      return cc;
    }
    
    /** Sets the value of the 'cc' field */
    public influent.idl.FL_GeoData.Builder setCc(java.lang.String value) {
      validate(fields()[3], value);
      this.cc = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'cc' field has been set */
    public boolean hasCc() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'cc' field */
    public influent.idl.FL_GeoData.Builder clearCc() {
      cc = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    public FL_GeoData build() {
      try {
        FL_GeoData record = new FL_GeoData();
        record.text = fieldSetFlags()[0] ? this.text : (java.lang.String) defaultValue(fields()[0]);
        record.lat = fieldSetFlags()[1] ? this.lat : (java.lang.Double) defaultValue(fields()[1]);
        record.lon = fieldSetFlags()[2] ? this.lon : (java.lang.Double) defaultValue(fields()[2]);
        record.cc = fieldSetFlags()[3] ? this.cc : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
